# Azure DevOps Pipeline with Veracode CLI Installer (Corrected)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CLI_FOLDER: "veracode"
  ARTIFACTS_FOLDER: "$(System.DefaultWorkingDirectory)/veracode-artifacts"

steps:
# Step 1: Greet the world
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 2: Clone the repository
- script: |
    echo "Cloning the repository: verademo-python"
    mkdir -p clonePath
    cd clonePath
    git clone https://github.com/eddemo0007/verademo-python.git
  displayName: 'Clone Repository: verademo-python'

# Step 3: Install Veracode CLI
- script: |
    echo "Installing Veracode CLI"
    curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    echo "Veracode CLI installed successfully."
    ls -lh # Check installed files
  displayName: 'Install Veracode CLI'

# Step 4: Package the source code for Veracode scanning
- script: |
    echo "Packaging source code for Veracode scan"
    mkdir -p $(ARTIFACTS_FOLDER)
    ./veracode --help || echo "Veracode CLI executable not found"
    ./veracode package --source clonePath/verademo-python/* --output $(ARTIFACTS_FOLDER) --trust --debug
  displayName: 'Package Source Code for Veracode'

# Step 5: Publish artifacts (optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(ARTIFACTS_FOLDER)'
    artifactName: 'veracode-artifacts'
    publishLocation: 'Container'
  displayName: 'Publish Veracode Artifacts'
