# Starter pipeline
# Start with a minimal pipeline that you can customize to build, test, and deploy your code.
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo "Cloning the repository: verademo-python"
    mkdir -p clonePath
    cd clonePath
    git clone https://github.com/eddemo0007/verademo-python.git
  displayName: 'Clone Repository: verademo-python'