# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
  CLI_FOLDER: "veracode"
  ARTIFACTS_FOLDER: "$(System.DefaultWorkingDirectory)/veracode-artifacts"
  SCAN_FILE: "$(ARTIFACTS_FOLDER)/veracode-auto-pack-verademo-python-python.zip"
  VERACODE_API_ID: "$(VERACODE_API_ID)"  # Set this as a secret variable in Azure DevOps
  VERACODE_API_KEY: "$(VERACODE_API_KEY)"  # Set this as a secret variable in Azure DevOps

steps:
# Step 1: Greet the world
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 2: Clone the repository
- script: |
    echo "Cloning the repository: verademo-python"
    mkdir -p clonePath
    cd clonePath
    git clone https://github.com/eddemo0007/verademo-python.git
  displayName: 'Clone Repository: verademo-python'

# Step 3: Install Veracode CLI
- script: |
    echo "Installing Veracode CLI"
    curl -fsS https://tools.veracode.com/veracode-cli/install | sh
    echo "Veracode CLI installed successfully."
    ls -lh # Check installed files
  displayName: 'Install Veracode CLI'

# Step 4: Package the source code for Veracode scanning
#     ./veracode package --source clonePath/verademo-python/* --output $(ARTIFACTS_FOLDER) --trust --debug
#- script: |
#    echo "Packaging source code for Veracode scan"
#    mkdir -p $(ARTIFACTS_FOLDER)
#    ./veracode package --source clonePath/verademo-python/* --output $(ARTIFACTS_FOLDER) --trust
#  displayName: 'Package Source Code for Veracode'

#- script: |
#    curl -O -L https://tools.veracode.com/integrations/API-Wrappers/Java/bin/VeracodeJavaAPI.zip
#    unzip -o VeracodeJavaAPI.zip -d veracode
#  displayName: 'Download and Extract Veracode Java API Wrapper'

- script: |
    java -jar veracode/VeracodeJavaAPI.jar \
      -vid '58902f130e5dc212f83b1da108928b56' \
      -vkey '1d282d5563c46035ab74e78befed3169d8be0e098a477321e27b629a88d82439cd00c3338d9cfccb87eae3b11276fa405f01dedb1855845fdd60bb3aaab58859' \
      -action uploadandscan \
      -appname 'Test0001' \
      -createprofile true \
      -filepath '$(SCAN_FILE)' \
      -version "$(SCAN_VERSION)" \
      -deleteincompletescan
  displayName: 'Upload and Scan with Veracode'
